stages:
  - test

variables:
  DOCKER_DRIVER: overlay2
  COMPOSE_PROJECT_NAME: portal
  PYTHONPATH: "$CI_PROJECT_DIR/backend"

before_script:
  - apt-get update -qy
  - apt-get install -y python3 python3-pip docker-compose

services:
  - docker:dind

test:
  stage: test
  script:
    - docker-compose -f docker-compose-prod.yml up -d --build
    - docker-compose exec portal-backend-1 coverage run --source='.' ./manage.py test
    - docker-compose exec portal-backend-1 coverage report
    - docker-compose exec portal-backend-1 bash -c "[ $(coverage report | awk '/TOTAL/ {print $NF}' | tr -d %) -ge 95 ]"