image: docker:stable
services:
  - docker:dind

stages:
  - test

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - apk add --update py-pip &&
    pip install docker-compose

test:
  stage: test
  script:
    - docker-compose up -d --build
    - docker-compose exec -it notification_service_django coverage run --source='.' ./manage.py test .