image: docker:stable
services:
  - docker:dind

stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - apk add --update py-pip &&
      pip install docker-compose
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/your_username/your_project_name .
    - docker push registry.gitlab.com/your_username/your_project_name
  only:
    - master

deploy:
  stage: test
  script:
    - docker exec portal-backend-1 coverage run --source='.' ./manage.py test
    - docker exec portal-backend-1 coverage report
    - docker exec portal-backend-1 bash -c "exit $(test $(coverage report | awk '/TOTAL/ {print $NF}' | tr -d %) -ge 95)"