stages:
  - test

variables:
  DOCKER_DRIVER: overlay2
  COMPOSE_PROJECT_NAME: portal
  PYTHONPATH: "$CI_PROJECT_DIR/backend"

before_script:
  - apt-get update -qy
  - apt-get install -y python3 python3-pip docker-compose

services:
  - docker:dind

test:
  stage: test
  script:
    - docker-compose up -d --build
    - docker-compose exec notification_service_django coverage run --source='.' ./manage.py test