stages:
  - test

variables:
  PYTHONPATH: "$CI_PROJECT_DIR/backend"

before_script:
  - apt-get update -qy
  - apt-get install -y python3 python3-pip
  - pip3 install docker-compose
  - docker-compose -f docker-compose-prod.yml build
  - docker-compose -f docker-compose-prod.yml up -d

test:
  stage: test
  script:
    - docker exec portal-backend-1 coverage run --source='.' ./manage.py test
    - docker exec portal-backend-1 coverage report
    - docker exec portal-backend-1 bash -c "exit $(test $(coverage report | awk '/TOTAL/ {print $NF}' | tr -d %) -ge 95)"