[tool.coverage.run]
omit = [
  "*/migrations/*",
  "backend/settings*",
  "manage.py",
  "*/apps.py",
  "backend/*sgi.py",
]

[tool.coverage.report]
exclude_lines = [
  "pragma: no ?cover",
  "def __str__",
]

[tool.black]
line-length = 120
extend-exclude = "migrations"
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
skip = ["migrations", "venv"]
line_length = 120
include_trailing_comma = true
profile = "black"
known_local_folder = ["src", "main"]