from .settings import *
from .settings import USE_HTTPS

CORS_ALLOWED_ORIGINS = ["http://" + i for i in ALLOWED_HOSTS]

X_FRAME_OPTIONS = "DENY"


if USE_HTTPS:
    CORS_ALLOWED_ORIGINS += ["https://" + i for i in ALLOWED_HOSTS]

    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # a year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_REFERRER_POLICY = "strict-origin"
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    USE_X_FORWARDED_HOST = True
