# Generated by Django 4.2.1 on 2023-11-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='task_ids',
            field=models.TextField(blank=True, null=True),
        ),
    ]
