# Generated by Django 4.2.1 on 2023-12-24 19:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0003_remove_mailing_task_ids_2_alter_mailing_task_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='task_ids',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=36), default=list, size=None
            ),
        ),
    ]
