name: Main

env:
  PROJECT_PATH: "/var/www/notification-service/"

on: workflow_dispatch

jobs:
  deploy-ssh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.VDS_PEM }}
          known_hosts: 'empty'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.VDS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: rsync -az . ${{ secrets.VDS_USER }}@${{ secrets.VDS_HOST }}:${{ env.PROJECT_PATH }}

      - name: Run build in the server
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd ${{ env.PROJECT_PATH }}
            docker compose -f docker-compose-prod.yml up -d --build
          host: ${{ secrets.VDS_HOST }}
          username: ${{ secrets.VDS_USER }}
          privateKey: ${{ secrets.VDS_PEM }}